name = "substring-search"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SubstringSearch"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0"

[[require]]
name = "Loom"
git = "https://github.com/verse-lab/loom.git"

[[lean_lib]]
name = "SubstringSearch"
